# IMPORT LIBRARIES  --------------------------------------------------------------------------------------------

import numpy as np  # useful for many scientific computing in Python
import pandas as pd # primary data structure library
import matplotlib as mpl
import matplotlib.pyplot as plt

# optional: for ggplot-like style
mpl.style.use('ggplot') 

# IMPORT DATA --------------------------------------------------------------------------------------------------

df_can = pd.read_csv('https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DV0101EN-SkillsNetwork/Data%20Files/Canada.csv')

# VISUALIZING DATA USING MATPLOTLIB ---------------------------------------------------------------------------

# Set Index
df_can.set_index('Country', inplace=True)

# Store the years in a variable
years = list(map(str, range(1980, 2014)))

# group countries by continents and apply sum() function 
df_continents = df_can.groupby('Continent').sum()

# print(df_continents)
# print(print(type(df_can.groupby('Continent', axis=0))))

# PIE CHARTS -------------------------------------------------------------------------------------------------

# View Immigration by continent

colors_list = ['gold', 'yellowgreen', 'lightcoral', 'lightskyblue', 'lightgreen', 'pink']
explode_list = [0.1, 0, 0, 0, 0.1, 0.1] # ratio for each continent with which to offset each wedge.

# autopct create %, start angle represent starting point
df_continents['Total'].plot(kind='pie',
                            figsize=(10, 6),
                            autopct='%1.1f%%', # add in percentages. 1 digit to the left of the decimal, & 1 to the right.
                            startangle=90,     # Rotate the start of the pie. start angle 90° (Africa)
                            shadow=True,       # add shadow      
                            labels=None,         # turn off labels on pie chart
                            pctdistance=1.11,    # the ratio between the center of each pie slice and the start of the text generated by autopct 
                            colors=colors_list,  # add custom colors
                            explode=explode_list # 'explode' lowest 3 continents
                            )

# scale the title up by 12% to match pctdistance
plt.title('Immigration to Canada by Continent [1980 - 2013]', y=1.085, fontsize = 15) 
plt.axis('equal') # Sets the pie chart to look like a circle.
plt.legend(labels=df_continents.index, loc='upper left') 
plt.show()

# BOX PLOTS -------------------------------------------------------------------------------------------------



# SCATTER PLOTS ---------------------------------------------------------------------------------------------



# BUBBLE PLOTS ----------------------------------------------------------------------------------------------



# PRINTS ----------------------------------------------------------------------------------------------------

# print(df_can.head())
# print(df_can.shape)

# check for latest version of Matplotlib
# print('Matplotlib version: ', mpl.__version__) # >= 2.0.0

# -----------------------------------------------------------------------------------------------------------