-- DDL statement for table 'HR' database--

DROP DATABASE IF EXISTS ibm7_db;
CREATE DATABASE ibm7_db;

USE ibm7_db;

-- Drop the tables in case they exist

DROP TABLE EMPLOYEES;
DROP TABLE JOB_HISTORY;
DROP TABLE JOBS;
DROP TABLE DEPARTMENTS;
DROP TABLE LOCATIONS;

-- Create the tables

CREATE TABLE EMPLOYEES (
    -- EMP_ID VARCHAR(50) NOT NULL,
    EMP_ID INT AUTO_INCREMENT NOT NULL,
    F_NAME VARCHAR(15) NOT NULL,
    L_NAME VARCHAR(15) NOT NULL,
    SSN CHAR(9),
    B_DATE DATE,
    SEX CHAR,
    ADDRESS VARCHAR(30),
    JOB_ID CHAR(9),
    SALARY DECIMAL(10,2),
    MANAGER_ID CHAR(9),
    DEP_ID CHAR(9) NOT NULL,
    PRIMARY KEY (EMP_ID)
  );

CREATE TABLE JOB_HISTORY (
    EMPL_ID CHAR(9) NOT NULL,
    START_DATE DATE,
    JOBS_ID CHAR(9) NOT NULL,
    DEPT_ID CHAR(9),
    PRIMARY KEY (EMPL_ID,JOBS_ID)
  );

CREATE TABLE JOBS (
    JOB_IDENT CHAR(9) NOT NULL,
    JOB_TITLE VARCHAR(30) ,
    MIN_SALARY DECIMAL(10,2),
    MAX_SALARY DECIMAL(10,2),
    PRIMARY KEY (JOB_IDENT)
  );

CREATE TABLE DEPARTMENTS (
    DEPT_ID_DEP CHAR(9) NOT NULL,
    DEP_NAME VARCHAR(15) ,
    MANAGER_ID CHAR(9),
    LOC_ID CHAR(9),
    PRIMARY KEY (DEPT_ID_DEP)
  );

CREATE TABLE LOCATIONS (
    LOCT_ID CHAR(9) NOT NULL,
    DEP_ID_LOC CHAR(9) NOT NULL,
    PRIMARY KEY (LOCT_ID,DEP_ID_LOC)
  );

-- LOADING DATA

LOAD DATA LOCAL INFILE './HR_DB CSV Files/Employees.csv' 
INTO TABLE EMPLOYEES
FIELDS TERMINATED BY ',';
-- LINES TERMINATED BY '\n';
-- OPTIONALLY ENCLOSED BY '"';
-- (@EMP_ID, F_NAME, L_NAME, SSN, B_DATE, SEX, ADDRESS, JOB_ID, SALARY, MANAGER_ID, DEP_ID)
-- SET EMP_ID = @EMP_ID;

LOAD DATA LOCAL INFILE './HR_DB CSV Files/JobsHistory.csv' 
INTO TABLE JOB_HISTORY
FIELDS TERMINATED BY ',';
LOAD DATA LOCAL INFILE './HR_DB CSV Files/Jobs.csv' 
INTO TABLE JOBS
FIELDS TERMINATED BY ',';
LOAD DATA LOCAL INFILE './HR_DB CSV Files/Departments.csv' 
INTO TABLE DEPARTMENTS
FIELDS TERMINATED BY ',';
LOAD DATA LOCAL INFILE './HR_DB CSV Files/Locations.csv' 
INTO TABLE LOCATIONS
FIELDS TERMINATED BY ',';

-- SHOW TABLES

SELECT * FROM EMPLOYEES;
SELECT * FROM JOB_HISTORY;
SELECT * FROM JOBS;
SELECT * FROM DEPARTMENTS;
SELECT * FROM LOCATIONS;

-- ACTIIVITIES



-- String Patterns --

-- SELECT F_NAME, L_NAME, DEP_ID, B_DATE
-- FROM EMPLOYEES
-- WHERE B_DATE LIKE '197%';
-- WHERE ADDRESS LIKE '%Elgin,IL%';
-- WHERE (SALARY BETWEEN 60000 AND 70000) AND DEP_ID = 5;

-- Sorting --

-- SELECT F_NAME, L_NAME, DEP_ID
-- FROM EMPLOYEES

-- ORDER BY DEP_ID;
-- ORDER BY DEP_ID DESC, L_NAME DESC;

-- Grouping

-- SELECT DEP_ID, COUNT(*)
-- FROM EMPLOYEES
-- GROUP BY DEP_ID;

-- SELECT DEP_ID, COUNT(*), AVG(SALARY)
-- FROM EMPLOYEES
-- GROUP BY DEP_ID;

-- SELECT DEP_ID, COUNT(*) AS "NUM_EMPLOYEES", AVG(SALARY) AS "AVG_SALARY"
-- FROM EMPLOYEES
-- GROUP BY DEP_ID;

-- SELECT DEP_ID, COUNT(*) AS "NUM_EMPLOYEES", AVG(SALARY) AS "AVG_SALARY"
-- FROM EMPLOYEES
-- GROUP BY DEP_ID
-- ORDER BY AVG_SALARY;

-- SELECT DEP_ID, COUNT(*) AS "NUM_EMPLOYEES", AVG(SALARY) AS "AVG_SALARY"
-- FROM EMPLOYEES
-- GROUP BY DEP_ID
-- HAVING count(*) < 4
-- ORDER BY AVG_SALARY;