DROP DATABASE IF EXISTS ibm6_db;
CREATE DATABASE ibm6_db;

USE ibm6_db;

DROP TABLE IF EXISTS PATIENTS;
DROP TABLE IF EXISTS MEDICAL_HISTORY;
DROP TABLE IF EXISTS MEDICAL_PROCEDURES;
DROP TABLE IF EXISTS MEDICAL_DEPARTMENTS;
DROP TABLE IF EXISTS MEDICAL_LOCATIONS;


CREATE TABLE PATIENTS (
  PATIENT_ID CHAR(9) NOT NULL,
  FIRST_NAME VARCHAR(15) NOT NULL,
  LAST_NAME VARCHAR(15) NOT NULL,
  SSN CHAR(9),
  BIRTH_DATE DATE,
  SEX CHAR,
  ADDRESS VARCHAR(30),
  DEPT_ID CHAR(9) NOT NULL,
  PRIMARY KEY (PATIENT_ID)
);

CREATE TABLE MEDICAL_HISTORY (
  MEDICAL_HISTORY_ID CHAR(9) NOT NULL,
  PATIENT_ID CHAR(9) NOT NULL,
  DIAGNOSIS_DATE DATE,
  DIAGNOSIS_CODE VARCHAR(10),
  MEDICAL_CONDITION VARCHAR(100),
  DEPT_ID CHAR(9),
  PRIMARY KEY (MEDICAL_HISTORY_ID)
);

CREATE TABLE MEDICAL_PROCEDURES (
  PROCEDURE_ID CHAR(9) NOT NULL,
  PROCEDURE_NAME VARCHAR(30),
  PROCEDURE_DATE DATE,
  PATIENT_ID CHAR(9) NOT NULL,
  DEPT_ID CHAR(9),
  PRIMARY KEY (PROCEDURE_ID)
);

CREATE TABLE MEDICAL_DEPARTMENTS (
  DEPT_ID CHAR(9) NOT NULL,
  DEPT_NAME VARCHAR(15),
  MANAGER_ID CHAR(9),
  LOCATION_ID CHAR(9),
  PRIMARY KEY (DEPT_ID)
);

CREATE TABLE MEDICAL_LOCATIONS (
  LOCATION_ID CHAR(9) NOT NULL,
  DEPT_ID CHAR(9) NOT NULL,
  LOCATION_NAME VARCHAR(50),
  PRIMARY KEY (LOCATION_ID, DEPT_ID)
);

LOAD DATA LOCAL INFILE 'PATIENTS.CSV' 
INTO TABLE PATIENTS
FIELDS TERMINATED BY ',';

LOAD DATA LOCAL INFILE 'MEDICAL_HISTORY.CSV' 
INTO TABLE MEDICAL_HISTORY
FIELDS TERMINATED BY ',';

LOAD DATA LOCAL INFILE 'MEDICAL_PROCEDURES.CSV' 
INTO TABLE MEDICAL_PROCEDURES
FIELDS TERMINATED BY ',';

LOAD DATA LOCAL INFILE 'MEDICAL_DEPARTMENTS.CSV' 
INTO TABLE MEDICAL_DEPARTMENTS
FIELDS TERMINATED BY ',';

LOAD DATA LOCAL INFILE 'MEDICAL_LOCATIONS.CSV' 
INTO TABLE MEDICAL_LOCATIONS
FIELDS TERMINATED BY ',';

SELECT * FROM PATIENTS;
SELECT * FROM MEDICAL_HISTORY ;
SELECT * FROM MEDICAL_PROCEDURES ;
SELECT * FROM MEDICAL_DEPARTMENTS ;
SELECT * FROM MEDICAL_LOCATIONS ;