DROP DATABASE IF EXISTS ibm_pets_db;
CREATE DATABASE ibm_pets_db;

USE ibm_pets_db;

DROP TABLE IF EXISTS PETSALE;
DROP TABLE IF EXISTS PET;
DROP TABLE IF EXISTS TOYS;

CREATE TABLE PETSALE (
  ID INTEGER NOT NULL,
  PET CHAR (20),
  SALEPRICE DECIMAL (6,2),
  PROFIT DECIMAL (6,2),
  SALEDATE DATE
);

CREATE TABLE PET (
  ID INTEGER NOT NULL,
  ANIMAL VARCHAR(20),
  QUANTITY INT
);

CREATE TABLE TOYS (
  ID INT NOT NULL,
  VARIETY VARCHAR(20),
  QUANTITY INT,
  PRIMARY KEY (ID)
);

INSERT INTO PETSALE VALUES
  (1,'Cat',450.09,100.47,'2018-05-29'),
  (2,'Dog',666.66,150.76,'2018-06-01'),
  (3,'Parrot',50.00,8.9,'2018-06-04'),
  (4,'Hamster',60.60,12,'2018-06-11'),
  (5,'Goldfish',48.48,3.5,'2018-06-14');

INSERT INTO PET VALUES
  (1,'Cat',3),
  (2,'Dog',4),
  (3,'Hamster',2);

INSERT INTO TOYS VALUES
(1,'Hamster Ball', 5),
(2,'Jump Rope', 10),
(3,'Marbles', 7);

-- ALTER TABLE PETSALE
-- ADD COLUMN QUANTITY INTEGER;

-- ALTER TABLE PETSALE
-- DROP COLUMN PROFIT;

-- ALTER TABLE PETSALE
-- MODIFY PET VARCHAR(20);

-- ALTER TABLE TOYS
-- MODIFY VARIETY CHAR(30);

-- TRUNCATE TABLE TOYS;

-- DROP TABLE TOYS;

-- ALTER TABLE `PETSALE` CHANGE `PET` `ANIMAL` varchar(20);

-- UPDATE PETSALE SET QUANTITY = 9 WHERE ID = 1;
-- UPDATE PETSALE SET QUANTITY = 3 WHERE ID = 2;
-- UPDATE PETSALE SET QUANTITY = 2 WHERE ID = 3;
-- UPDATE PETSALE SET QUANTITY = 6 WHERE ID = 4;
-- UPDATE PETSALE SET QUANTITY = 24 WHERE ID = 5;

-- TRUNCATE TABLE PET;
-- DROP TABLE PET;

SELECT * FROM PETSALE;
SELECT * FROM PET;
SELECT * FROM TOYS;